### ISSUE TITLE
pickle error when saving checkpoints

### ISSUE THREAD

**Issue by yiulau** [Sachin19/seq2seq-con#6]
When I run `train.py` 

`python ~/seq2seq-con/train.py -gpus 0 -data ./data/data.pt.train.pt -layers 2 -rnn_size 512 -word_vec_size 512 -output_emb_size 300 -brnn -loss nllvmf -epochs 2 -optim adam -dropout 0.0 -learning_rate 0.    0005 -log_interval 100 -save_model my_nll -batch_size 64 -tie_emb`

I get an error like this 

```
Namespace(batch_size=64, brnn=True, brnn_merge='concat', curriculum=False, data='./data/data.pt.train.pt', dropout=0.0, epochs=2, extra_shuffle=False, fix_src_emb=False, gpus=[0], input_feed=1, layers=2, learning_rate=0.0005, learning_rate_decay=0.5, log_interval=100, loss='nllvmf', max_generator_batches=32, max_grad_norm=5, nonlin_gen=False, optim='adam', output_emb_size=300, param_init=0.1, pre_word_vecs_dec=None, pre_word_vecs_enc=None, pre_word_vecs_output=None, rnn_size=512, save_all_epochs=False, save_model='my_nll', start_decay_at=8, start_epoch=1, tie_emb=True, train_anew=False, train_from='', train_from_state_dict='', word_vec_size=512)
Loading data from './data/data.pt.train.pt'
 * vocabulary size. source = 50004; target = 50000
 * number of training sentences. 234036
 * maximum batch size. 64
Building model...
* number of trainable parameters: 35101484
NMTModel(
  (encoder): Encoder(
    (word_lut): Embedding(50004, 512, padding_idx=0)
    (rnn): LSTM(512, 256, num_layers=2, bidirectional=True)
  )
  (decoder): Decoder(
    (word_lut): Embedding(50000, 300)
    (emb2input): Linear(in_features=300, out_features=512, bias=True)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.0)
      (layers): ModuleList(
        (0): LSTMCell(1024, 512)
        (1): LSTMCell(512, 512)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=512, out_features=512, bias=False)
      (sm): Softmax()
      (linear_out): Linear(in_features=1024, out_features=512, bias=False)
      (tanh): Tanh()
    )
    (dropout): Dropout(p=0.0)
  )
  (generator): Sequential(
    (0): Linear(in_features=512, out_features=300, bias=True)
  )
)
/home/yiu/seq2seq-con/onmt/Dataset.py:68: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  b = Variable(b, volatile=self.volatile)
/home/yiu/seq2seq-con/loss.py:16: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  outputs = Variable(outputs.data, requires_grad=(not eval), volatile=eval)
Validation per step loss: -427.31
Validation per step other loss: 0.99006

/home/yiu/seq2seq-con/onmt/Optim.py:35: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  clip_grad_norm(self.params, self.max_grad_norm)
Epoch  1,   100/ 3657; lps: -428.01404; mse_lps: 0.56763; 12928 src tok/s; 12733 tgt tok/s; 668 sample/s;     10 s elapsed
Epoch  1,   200/ 3657; lps: -428.17770; mse_lps: 0.49556; 14156 src tok/s; 13699 tgt tok/s; 631 sample/s;     21 s elapsed
Epoch  1,   300/ 3657; lps: -428.24899; mse_lps: 0.46586; 14040 src tok/s; 13645 tgt tok/s; 641 sample/s;     31 s elapsed
Epoch  1,   400/ 3657; lps: -428.29535; mse_lps: 0.44727; 13836 src tok/s; 13412 tgt tok/s; 670 sample/s;     40 s elapsed
Epoch  1,   500/ 3657; lps: -428.33740; mse_lps: 0.43049; 14208 src tok/s; 13678 tgt tok/s; 595 sample/s;     51 s elapsed
Epoch  1,   600/ 3657; lps: -428.38971; mse_lps: 0.40920; 14407 src tok/s; 14027 tgt tok/s; 630 sample/s;     61 s elapsed
Epoch  1,   700/ 3657; lps: -428.43015; mse_lps: 0.39302; 13909 src tok/s; 13532 tgt tok/s; 622 sample/s;     71 s elapsed
Epoch  1,   800/ 3657; lps: -428.47525; mse_lps: 0.37523; 13679 src tok/s; 13319 tgt tok/s; 659 sample/s;     81 s elapsed
Epoch  1,   900/ 3657; lps: -428.47098; mse_lps: 0.37668; 14284 src tok/s; 13836 tgt tok/s; 613 sample/s;     91 s elapsed
Epoch  1,  1000/ 3657; lps: -428.51727; mse_lps: 0.35823; 13618 src tok/s; 13353 tgt tok/s; 675 sample/s;    101 s elapsed
Epoch  1,  1100/ 3657; lps: -428.51468; mse_lps: 0.35920; 14259 src tok/s; 13923 tgt tok/s; 629 sample/s;    111 s elapsed
Epoch  1,  1200/ 3657; lps: -428.54184; mse_lps: 0.34848; 13945 src tok/s; 13549 tgt tok/s; 626 sample/s;    121 s elapsed
Epoch  1,  1300/ 3657; lps: -428.54544; mse_lps: 0.34690; 14336 src tok/s; 13912 tgt tok/s; 620 sample/s;    132 s elapsed
Epoch  1,  1400/ 3657; lps: -428.55545; mse_lps: 0.34304; 14013 src tok/s; 13677 tgt tok/s; 632 sample/s;    142 s elapsed
Epoch  1,  1500/ 3657; lps: -428.59375; mse_lps: 0.32786; 13999 src tok/s; 13636 tgt tok/s; 645 sample/s;    152 s elapsed
Epoch  1,  1600/ 3657; lps: -428.58691; mse_lps: 0.33046; 14409 src tok/s; 13871 tgt tok/s; 593 sample/s;    162 s elapsed
Epoch  1,  1700/ 3657; lps: -428.60376; mse_lps: 0.32374; 14253 src tok/s; 13859 tgt tok/s; 609 sample/s;    173 s elapsed
Epoch  1,  1800/ 3657; lps: -428.61404; mse_lps: 0.31958; 14372 src tok/s; 13931 tgt tok/s; 620 sample/s;    183 s elapsed
Epoch  1,  1900/ 3657; lps: -428.62067; mse_lps: 0.31684; 14278 src tok/s; 13859 tgt tok/s; 621 sample/s;    194 s elapsed
Epoch  1,  2000/ 3657; lps: -428.62711; mse_lps: 0.31431; 14500 src tok/s; 14006 tgt tok/s; 612 sample/s;    204 s elapsed
Epoch  1,  2100/ 3657; lps: -428.64532; mse_lps: 0.30712; 13907 src tok/s; 13592 tgt tok/s; 637 sample/s;    214 s elapsed
Epoch  1,  2200/ 3657; lps: -428.65009; mse_lps: 0.30508; 14166 src tok/s; 13633 tgt tok/s; 615 sample/s;    225 s elapsed
Epoch  1,  2300/ 3657; lps: -428.67178; mse_lps: 0.29664; 12135 src tok/s; 11900 tgt tok/s; 636 sample/s;    235 s elapsed
Epoch  1,  2400/ 3657; lps: -428.66647; mse_lps: 0.29864; 13683 src tok/s; 13340 tgt tok/s; 657 sample/s;    244 s elapsed
Epoch  1,  2500/ 3657; lps: -428.69794; mse_lps: 0.28635; 13363 src tok/s; 13059 tgt tok/s; 716 sample/s;    253 s elapsed
Epoch  1,  2600/ 3657; lps: -428.68912; mse_lps: 0.28969; 13630 src tok/s; 13356 tgt tok/s; 687 sample/s;    263 s elapsed
Epoch  1,  2700/ 3657; lps: -428.68018; mse_lps: 0.29306; 14002 src tok/s; 13687 tgt tok/s; 666 sample/s;    272 s elapsed
Epoch  1,  2800/ 3657; lps: -428.67957; mse_lps: 0.29320; 14343 src tok/s; 13920 tgt tok/s; 622 sample/s;    282 s elapsed
Epoch  1,  2900/ 3657; lps: -428.69455; mse_lps: 0.28743; 13715 src tok/s; 13484 tgt tok/s; 680 sample/s;    292 s elapsed
Epoch  1,  3000/ 3657; lps: -428.68796; mse_lps: 0.28988; 13785 src tok/s; 13397 tgt tok/s; 655 sample/s;    302 s elapsed
Epoch  1,  3100/ 3657; lps: -428.69406; mse_lps: 0.28747; 14149 src tok/s; 13791 tgt tok/s; 647 sample/s;    312 s elapsed
Epoch  1,  3200/ 3657; lps: -428.70630; mse_lps: 0.28273; 13777 src tok/s; 13421 tgt tok/s; 666 sample/s;    321 s elapsed
Epoch  1,  3300/ 3657; lps: -428.70053; mse_lps: 0.28483; 14535 src tok/s; 14166 tgt tok/s; 627 sample/s;    331 s elapsed
Epoch  1,  3400/ 3657; lps: -428.71848; mse_lps: 0.27790; 13991 src tok/s; 13669 tgt tok/s; 652 sample/s;    341 s elapsed
Epoch  1,  3500/ 3657; lps: -428.71857; mse_lps: 0.27776; 13829 src tok/s; 13620 tgt tok/s; 678 sample/s;    351 s elapsed
Epoch  1,  3600/ 3657; lps: -428.71576; mse_lps: 0.27881; 14597 src tok/s; 14136 tgt tok/s; 618 sample/s;    361 s elapsed
Epoch  1, 234036 samples,    367 s
Train per step loss: -428.563
Validation per step loss: -428.625
Validation per step other loss: 0.312244
Traceback (most recent call last):
  File "/home/yiu/seq2seq-con/train.py", line 437, in <module>
    main()
  File "/home/yiu/seq2seq-con/train.py", line 434, in main
    trainModel(model, trainData, validData, dataset, target_embeddings, optim)
  File "/home/yiu/seq2seq-con/train.py", line 290, in trainModel
    '%s_latest.pt' % (opt.save_model))
  File "/home/yiu/.conda/envs/yiuenv/lib/python3.7/site-packages/torch/serialization.py", line 224, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/yiu/.conda/envs/yiuenv/lib/python3.7/site-packages/torch/serialization.py", line 149, in _with_file_like
    return body(f)
  File "/home/yiu/.conda/envs/yiuenv/lib/python3.7/site-packages/torch/serialization.py", line 224, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/yiu/.conda/envs/yiuenv/lib/python3.7/site-packages/torch/serialization.py", line 297, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'Optim.set_parameters.<locals>.<lambda>'
```

The error seems to come from the `params` attribute of the `optim` object, which is a lambda function.

**Comment by Sachin19** [comment]
This could be because you are using a different version of python (3.7) than the recommended one (2.7). You could try removing the optimizer from the save object.

**Comment by yiulau** [comment]
Thanks! I found out I all I had to do was to replace `filter(...) `by `list(filter(...))` to get it to work in python 3.7.
