### ISSUE TITLE
error running translate.py

### ISSUE THREAD

**Issue by yiulau** [Sachin19/seq2seq-con#7]
I ran `translate.py` with the source and target files generated by ` prepare_data.py` as 
`python ~/seq2seq-con/translate.py -loss nllvmf -gpu 0 -model ./my_nll_bestmodel.pt -src ./data/dev.tok.true.fr -tgt ./data/dev.tok.true.en -replace_unk -output ./data/predictions -batch_size 512 -beam_size 1`

and I got this error 
```
Namespace(batch_size=512, beam_size=1, cuda=True, gpu=0, lookup_dict=None, loss='nllvmf', max_sent_length=100, model='./my_nll_bestmodel.pt', n_best=1, output='./data/predictions', replace_unk=True, saved_lm='', src='./data/dev.tok.true.fr', tgt='./data/dev.tok.true.en', tgt_dict=None, use_lm=False, verbose=False)
/home/yiu/seq2seq-con/onmt/Dataset.py:68: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  b = Variable(b, volatile=self.volatile)
/home/yiu/seq2seq-con/onmt/Translator.py:258: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  input_var = Variable(input_, volatile=True)
/home/yiu/seq2seq-con/onmt/Translator.py:311: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  .view(*newSize), volatile=True)
Traceback (most recent call last):
  File "/home/yiu/seq2seq-con/translate.py", line 152, in <module>
    main()
  File "/home/yiu/seq2seq-con/translate.py", line 100, in main
    predBatch, predScore, knntime_ = translator.translate(srcBatch, tgtBatch)
  File "/home/yiu/seq2seq-con/onmt/Translator.py", line 351, in translate
    [self.buildTargetTokens(pred[b][n], srcBatch[b], attn[b][n]) for n in range(self.opt.n_best) ]
  File "/home/yiu/seq2seq-con/onmt/Translator.py", line 351, in <listcomp>
    [self.buildTargetTokens(pred[b][n], srcBatch[b], attn[b][n]) for n in range(self.opt.n_best) ]
  File "/home/yiu/seq2seq-con/onmt/Translator.py", line 151, in buildTargetTokens
    if isNumeral(tokens[i]):
  File "/home/yiu/seq2seq-con/onmt/Translator.py", line 12, in isNumeral
    x = re.findall(r'[0-9]+[\.,][0-9]+',s)
  File "/home/yiu/.conda/envs/yiuenv/lib/python3.7/re.py", line 223, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object

```

**Comment by Sachin19** [comment]
You are using Python 3.7 instead of the recommended 2.7 which is causing this error. One way to work around this error is to cast `s` in line 12 of `"/home/yiu/seq2seq-con/onmt/Translator.py"` to a string type.

**Comment by yiulau** [comment]
Then I got this error
```
Namespace(batch_size=512, beam_size=1, cuda=True, gpu=0, lookup_dict=None, loss='nllvmf', max_sent_length=100, model='./my_nll_bestmodel.pt', n_best=1, output='./data/predictions', replace_unk=True, saved_lm='', src='./data/dev.tok.true.fr', tgt='./data/dev.tok.true.en', tgt_dict=None, use_lm=False, verbose=False)
/home/yiu/seq2seq-con/onmt/Dataset.py:68: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  b = Variable(b, volatile=self.volatile)
/home/yiu/seq2seq-con/onmt/Translator.py:259: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  input_var = Variable(input_, volatile=True)
/home/yiu/seq2seq-con/onmt/Translator.py:312: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  .view(*newSize), volatile=True)
Traceback (most recent call last):
  File "/home/yiu/seq2seq-con/translate.py", line 152, in <module>
    main()
  File "/home/yiu/seq2seq-con/translate.py", line 113, in main
    outF.write(" ".join(predBatch[b][0]) + '\n')
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by Sachin19** [comment]
It's hard for me to pinpoint the reason for this error. The easiest way to make everything work is using Python 2.7. Just run your code using as `python2 translate.py ...` instead of `python translate.py ...` (you might need to reinstall some libraries though)

**Comment by yiulau** [comment]
It is actually a Pytorch version issue, more specifically the way it deals with 0-dimensional tensors. I am trying to get the code to run on PyTorch 1.1 and on Python 3.7. Do you have a PyTorch 1.1 compatible version of the code?

**Comment by Sachin19** [comment]
I see, I don't think this code is compatible with Pytorch 1.1. We are planning on releasing a newer version of this code (compatible with Python >=3 and Pytorch >=1) in a few weeks.
